### ISSUE TITLE
Can't load avatar textures in pakaged build

### ISSUE THREAD

**Issue by lehuan5062** [readyplayerme/rpm-unreal-avatar-creator#33]
# Describe the bug
After I package your example, I can load avatar textures when playing the avatar creator map in the build.
But when I package my project, I can't.

# To Reproduce
1. Create third person C++ project.
2. Add plugins ready player me, avatar creator and glTF plugins.
3. Migrate the avatar creator widget and game mode from example project.
4. Package the project using Project Launcher tool
5. Play.

# Expected behavior
Avatar textures should be loaded properly.

# Screenshots
https://github.com/readyplayerme/rpm-unreal-avatar-creator/assets/65440815/4dc649dc-7cd1-45eb-827a-9efeb9f1fc44

# Desktop (please complete the following information):
 - RpmAvatarCreator plugin version: https://github.com/readyplayerme/rpm-unreal-avatar-creator/tree/5e67a9727383b3548cf4579b9ed28da6ef4ea123
 - ReadyPlayerMe plugin version: https://github.com/readyplayerme/rpm-unreal-sdk/tree/3313e5c47105f52744b6d401049ce8279ea4269f
 - glTFRuntime plugin version: https://github.com/rdeioris/glTFRuntime/tree/0b67abfd22f873c06fd8abee6b68f5696a535e96
 - Unreal Engine version 5.0.3
 - Operating System: Windows
 - Platform: Windows Build

**Comment by gadamyan** [comment]
Please add the /glTFRuntime to the te additional asset directories to cook. We will automate this process in the next release.
[Docs](https://docs.readyplayer.me/ready-player-me/integration-guides/unreal-engine/troubleshooting/crashes-on-built-applications)

**Comment by lehuan5062** [comment]
Thank you. I would like to contribute the automation: https://github.com/readyplayerme/rpm-unreal-sdk/pull/30
