### ISSUE TITLE
This no longer works in UE5.1.1.

### ISSUE THREAD

**Issue by Connorado07** [readyplayerme/rpm-unreal-avatar-creator#6]
When enabling the Avatar Creator UE5 plugin, it gives you the following error after restarting the editor when enabling the plugin:

**Files**

![RPMAvatarCreatorPluginError](https://user-images.githubusercontent.com/77865401/232254904-020b33b6-1e14-4548-9350-ae307faa68d0.png)

1. Install the plugin by downloading the latest release, copying the plugin folder from the template project, paste in the UE5.1 Engine/Plugins folder.
2. Launch UE5.1.1 and enable the Avatar Creator Plugin
3. Click Restart Editor and wait for restart.
4. Viola! 

Based on the README and the ReadyPlayer.me documentation, the editor should launch normally.

**Desktop (please complete the following information):**
 - RpmAvatarCreator plugin version: 0.1.0
 - ReadyPlayerMe plugin version: (Couldnt find version name. Date 3/2/2023)
 - glTFRuntime plugin version: (Couldnt find version name. Date 3/2/2023)
 - Unreal Engine version: UE 5.1.1
 - Operating System: Windows 11 Pro
 - Platform: Editor

**Comment by gadamyan** [comment]
Please use the [v0.2.0](https://github.com/readyplayerme/rpm-unreal-avatar-creator/releases/tag/v0.2.0) of the Avatar Creator
